### ISSUE TITLE
WASI support

### ISSUE THREAD

**Issue by tessi** [tessi/wasmex#17]
Using the latest changes on master it should be possible to implement the [WASI interface](https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md). But it would be great if we could get [the default implementations for WASI functions from wasmer](https://github.com/wasmerio/wasmer/blob/8c174554568c716fe3d0530a7ebb2fb4f9f4b023/lib/wasi/src/lib.rs).

When instantiating a new module, we could pass an extra map which could be a WASI-flag. Maybe something like this:

```elixir
imports = %{
  env: %{
    sum: {:fn, [:i32, :i32], [:i32], fn context, a, b -> a + b end}
  }
}

wasi = %{
  args: ["param1", "param2]
  env: %{"ENV_NAME" => "env_value"}
}

instance = start_supervised!({Wasmex, %{bytes: @import_test_bytes, imports: imports, wasi: wasi}})
```

**Comment by tessi** [comment]
The WIP PR to implement this is up at #18

**Comment by tessi** [comment]
Update: The WIP solution is probably good enough, but the tests cannot run due to a bug in wasmer. Since the wasmer team is currently rewriting the whole implementation I will see whether porting to that rewrite will make the bug go away (esp. since the bug is very unlikely to be fixed in the old wasmer codebase).

**Comment by autodidaddict** [comment]
Has there been any activity on the wasmer front to let you move forward with the WASI implementation?

**Comment by tessi** [comment]
Hey @autodidaddict 👋 
thanks for asking and being interested :) I wrote further updates in the PR ([this is the latest update](https://github.com/tessi/wasmex/pull/18#issuecomment-775783975)). Sorry for letting this issue hang for such a long time.

The brief summary is: I'm missing only a few things on the technical side. What's keeping me from finishing this is getting enough free time to work on it myself. I'd be happy for anyone taking on a code review, adding a missing feature/test, giving feedback from a users perspective (trying out WASI support from the PR), or just talking/chatting about details.

I don't necessarily mean you have to do all that, of course ;) Just getting my thoughts out to whoever reads this and considers contributing.

**Comment by tessi** [comment]
I finished the WASI implementation and it seems to work quite nicely for me. The PR was just merged, I'd be interested in your results if you try this out. As always, feel free to open another issue if there is any questions or bugs.
