### ISSUE TITLE
Support rustler 0.22.0-rc1

### ISSUE THREAD

**Issue by autodidaddict** [tessi/wasmex#257]
When you upgrade to OTP 24, rustler 0.21 breaks (thread panic at `Erlang version 2.16 not handled, please file a a bug report.`) as does wasmex due to its reliance on that version of rustler. If wasmex can upgrade to this new rc, then I can get my code to build on the newest version of Rustler (which has some pretty great syntax upgrades).

**Comment by tessi** [comment]
Thanks for reporting the issue and sorry for letting you wait a while. now that rustler 0.22.0 was released and I found some time, I could do the rustler upgrade.

I immediately released 0.4.0 so you can (hopefully) just update and enjoy. 👉  https://hex.pm/packages/wasmex/0.4.0
