### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by tessi** [tessi/wasmex#317]
we use circle ci as a CI service, and they are great. However, in other projects I'm working on we're using GH actions mostly and switching over means I have to keep less things in mind.

This is very subjective and purely to reduce maintenance overhead just a tiny bit.

**Comment by fahchen** [comment]
We may need to remove this repo from CircleCI, for it fails after the config file removed.


<img width="745" alt="image" src="https://user-images.githubusercontent.com/855678/160234280-45206bfc-462d-4584-a953-61a694f74b4a.png">
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/855678/160234324-b774e4f9-d606-486b-b72a-e5b66f4bf37a.png">

**Comment by tessi** [comment]
Thanks for noticing! I just disabled circle ci
