### ISSUE TITLE
Offer precompiled wasmex binaries

### ISSUE THREAD

**Issue by tessi** [tessi/wasmex#318]
With [recent work from dashbit](https://dashbit.co/blog/rustler-precompiled) it is now possible to have precompiled rustler binaries. I want to offer that with wasmex, so people don't have to have a rust compiler installed to use it (for most archs)

**Comment by fahchen** [comment]
Should we change the dev version to a pre release version like (like `0.6.1-dev`) ?
According to the [rustler_precompiled document](https://hexdocs.pm/rustler_precompiled/precompilation_guide.html#the-rustler-module), it forces the build by using a pre release version, or we force to build by a flag.

1. by setting the system env var:
```
WASMEX_BUILD=true mix compile --force
```
2. by setting an application env:
```
config :rustler_precompiled, :force_build, wasmex: true
```

**Comment by tessi** [comment]
I'm a fan setting a flag. This gives users control on whether they trust the precompiled binaries or not. It is also more explicit.

My gut feeling is to use approach 1. (probably follow what [html5ever_elixir](https://github.com/rusterlium/html5ever_elixir/search?q=HTML5EVER_BUILD) did, they are rustler devs and I assume they know what they're doing :))

**Comment by fahchen** [comment]
> 

I introduce the `WASMEX_BUILD` flag, and set this flag `true` in the CI.
Have a look at https://github.com/tessi/wasmex/pull/321
