### ISSUE TITLE
Require at least elixir 1.11

### ISSUE THREAD

**Issue by tessi** [tessi/wasmex#324]
We just loosened our elixir requirement to `~1.10`, but it seems dependencies need at least `1.11` - it more than just rustler, but here is a compile warning for `rustler` as an example:

```
==> rustler
Compiling 7 files (.ex)
Generated rustler app
warning: the dependency :rustler_precompiled requires Elixir "~> 1.11" but you are running on v1.10.4
```

**Comment by tessi** [comment]
@fahchen just FYI, as you did the work to support elixir 1.10. Is there any reason you need 1.10 support or are you OK with supporting roughly the last three releases of OTP/elixir?

```
otp: [22.3, 23.3, 24.3]
elixir: [1.11.4, 1.12.3, 1.13.3]
```

**Comment by fahchen** [comment]
> @fahchen just FYI, as you did the work to support elixir 1.10. Is there any reason you need 1.10 support or are you OK with supporting roughly the last three releases of OTP/elixir?
> 
> 
> 
> ```
> 
> otp: [22.3, 23.3, 24.3]
> 
> elixir: [1.11.4, 1.12.3, 1.13.3]
> 
> ```

It's ok for me to support last three releases of OTP/Elixir. I just loose the Elixir requirement and pass the compatibility CI rather than any efforts.
I didn't notice the compile warning at all, maybe we can add `--warnings-as-errors` to fail the compatibility CI at that case.

**Comment by tessi** [comment]
great, I'll leave it at 1.11.4 as the oldest supported version then. Adding `--warnings-as-errors` is a good idea!
