### ISSUE TITLE
Allow call_function to accept longer GenServer timeouts

### ISSUE THREAD

**Issue by autodidaddict** [tessi/wasmex#332]
By default, a `GenServer.call` assumes a timeout of `5_000`. In some edge cases (for example, a wasm module that's doing a lot of I/O by way of the host runtime like wasmCloud) we might have a function that takes more than 5 seconds to finish.

We should be able to just provide an optional / default timeout parameter to the function in the following link, right? If this is already possible and I'm just not good at GenServers, please let me know :)
https://github.com/tessi/wasmex/blob/main/lib/wasmex.ex#L216

**Comment by tessi** [comment]
thanks for raising this issue and contributing the solution 💜
