### ISSUE TITLE
Ability to cache compiled modules

### ISSUE THREAD

**Issue by munjalpatel** [tessi/wasmex#358]
Is it possible ( and practical ) to cache compiled modules and then load them at a later point? Especially for large wasm files?

Something like the following?

```ex
{:ok, bytes } = File.read("wasmex_test.wasm")
{:ok, module} = Wasmex.Module.compile(bytes)

### cache and load ###
{:ok} = cache_to_disk(module, path)
{:ok, module} = load_from_disk(path)

{:ok, instance } = Wasmex.start_link(%{module: module}) # starts a GenServer running this WASM instance

{:ok, [42]} == Wasmex.call_function(instance, "sum", [50, -8])
```

**Comment by tessi** [comment]
Hey @munjalpatel good question!

yes, it is. compilation takes some time and resources, re-using a precompiled module makes sense as you suggested.

Have a look at [`Module.serialize\1`](https://hexdocs.pm/wasmex/Wasmex.Module.html#serialize/1) and [`Module.unsafe_deserialize\1`](https://hexdocs.pm/wasmex/Wasmex.Module.html#unsafe_deserialize/1) they (de-)serialize a compiled module into a binary (which you can store wherever you want).

Hope our docs help you out and that hint solves your problem :)

**Comment by munjalpatel** [comment]
I hope you had a great vacation! This is very helpful, thanks @tessi !
