### ISSUE TITLE
How safe is it to run untrusted user wasm modules?

### ISSUE THREAD

**Issue by munjalpatel** [tessi/wasmex#360]
_This is a general question and not a bug report_

We have a need to run custom data-transform logic from users in our data platform.
We are interested in utilizing WASM due to its super quick start-up times and sandboxed nature.

However, is it practical? What are some additional security concerns we should be mindful of specifically when it comes to Elixir + WASM using `wasmex`

Another project we are considering is Lunatic ( https://github.com/lunatic-solutions/lunatic )
However, we would rather avoid dealing with Rust as much as we can.

Thanks!

**Comment by tessi** [comment]
In general, I'd it is pretty safe. In detail it's complicated and depends not only on wasmex, but also on the WASM engine we use and your application code :) I didn't do any professional pentests or anything with wasmex, but it is used by some apps in production already. So I'm not the only one trusting my code ;)

The WASM engines we base upon (currently wasmer, likely wasmtime in the next major version) are doing [a pretty good job](https://bytecodealliance.org/articles/security-and-correctness-in-wasmtime) in securing their part.

Wasmex is a wrapper around that engine using a [NIF](https://www.erlang.org/doc/tutorial/nif.html) which has [some security implications](https://www.erlang.org/doc/man/erl_nif.html), mostly:

1. If the NIF crashes, it brings the Erlang VM down. We secure against this by using Rust, which [is known to be pretty secure in that regard](https://msrc-blog.microsoft.com/2019/07/22/why-rust-for-safe-systems-programming/)
2. illegal Data/Memory access: which we guard against by using WASM in the first place (sandboxing + object capability model)
3. DOS/resource depletion attacks: Currently it is possible for your users to provide a WASM file with an endless loop which might deplete a CPU core. Guarding against this is a feature I very much like to add after our migration to wasmtime. They have a concept of ["fuel" consumed](https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html#method.add_fuel) by WASM execution which limits the resources your users code can use. I'm very open to PRs and more discussion in that direction.


Hope this helps :)

**Comment by munjalpatel** [comment]
Thanks, @tessi , this is helpful. I'll try this out when I get a chance and open PRs where it makes sense.
