### ISSUE TITLE
Seems like rust is a prerequisite?

### ISSUE THREAD

**Issue by superchris** [tessi/wasmex#398]
I was unable to use wasmex, got a pretty cryptic error about an ets table entry being invalid. I didn't save it, apologies. When I added rust to my asdf .tool-versions file I was able to startup my project. This seems to imply rust is a dependency to use wasmex, if so it would be good to add to README.

**Comment by tessi** [comment]
Hey @superchris - thanks for opening this issue and apologies for replying that late. Have you encountered this error again?

For most platforms, we provide precompiled binaries so Rust isn't needed unless you install from source or on an unsupported platform.
