### ISSUE TITLE
call_function example does not behave as expected

### ISSUE THREAD

**Issue by kimjarvis** [tessi/wasmex#406]
The function does not produces the [result described in the documentation](https://hexdocs.pm/wasmex/Wasmex.html#call_function/4).

I expected the response described in the documentation: `{:ok, [42]}`.  Returning the value 42 is the purpose of the example.  Instead,  the function returned `{:ok, '*'}`. 

On master branch and v0.8.2 tag.
Observed on MacOS 13.1 and Ubuntu 22.04.

```bash
iex(1)> wat = "(module
...(1)> (func $helloWorld (result i32) (i32.const 42))
...(1)>  (export \"hello_world\" (func $helloWorld))
...(1)>     )"
"(module\n(func $helloWorld (result i32) (i32.const 42))\n (export \"hello_world\" (func $helloWorld))\n    )"
iex(2)> {:ok, pid} = Wasmex.start_link(%{bytes: wat})
{:ok, #PID<0.667.0>}
iex(3)> Wasmex.call_function(pid, "hello_world", [])
{:ok, '*'}
```

Similarly, the [specifying a timeout](https://hexdocs.pm/wasmex/Wasmex.html#call_function/4-specifying-a-timeout) example does not return the expected value `{:ok, [42]}`.

```
iex(13)> wat = "(module
...(13)> (func $helloWorld (result i32) (i32.const 42))
...(13)> (export \"hello_world\" (func $helloWorld))
...(13)>  )"
"(module\n(func $helloWorld (result i32) (i32.const 42))\n(export \"hello_world\" (func $helloWorld))\n )"
iex(14)> {:ok, pid} = Wasmex.start_link(%{bytes: wat})
{:ok, #PID<0.4420.0>}
iex(15)> Wasmex.call_function(pid, "hello_world", [], 10_000)
{:ok, '*'}
```

**Comment by ammmir** [comment]
`*` is the ASCII representation of 42, but it doesn't explain why it's being returned as `'*'` and not `[42]`. if you substitute it for another number, say 1, it returns a list `[1]`. this feels like some erlang auto-ASCIIfication going on somewhere, but i can't figure out quickly.  the native [execute_function](https://github.com/tessi/wasmex/blob/6594e2c1d592c0c58f72200d4eb2285b33c0f327/native/wasmex/src/instance.rs#L188-L215) seems like it should be returning a list...

**Comment by tessi** [comment]
Hey @kimjarvis. Thanks for opening the issue upon observing an inconsistency.

@ammmir is right here. Wasmex indeed returns a list of numbers, but this specific list happens to contain only valid ASCII codepoints by accident and, thus, is _also_ a charlist.  [A charlist](https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists) is "a list of integers where all the integers are valid code points". They are printed slightly different in the Elixir REPL. So `[42]` and `'*'` are indeed equal as demonstrated in the following examples:

```elixir
iex(1)> [42]
'*'
```

and

```elixir
iex(2)> [42] == '*'
true
```

[The elixir docs](https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists) have a quote for your exact situation:

> Interpreting integers as code points may lead to some surprising behavior. For example, if you are storing a list of integers that happen to range between 0 and 127, by default IEx will interpret this as a charlist and it will display the corresponding ASCII characters.
>
> ```elixir
> iex> heartbeats_per_minute = [99, 97, 116]
> 'cat'
> ```

In that sense I'll close with:

```elixir
[97, 112, 111, 108, 111, 103, 105, 101, 115, 32, 102, 111, 114, 32, 109, 121, 32, 108, 97, 116, 101, 32, 114, 101, 112, 108, 121, 32, 97, 103, 97, 105, 110, 32, 97, 110, 100, 32, 116, 104, 97, 110, 107, 115, 32, 102, 111, 114, 32, 111, 112, 101, 110, 105, 110, 103, 32, 116, 104, 101, 32, 105, 115, 115, 117, 101, 33]
```

:)

I'll consider this issue closed as not being a problem with Wasmex.
