### ISSUE TITLE
unknown import: `wasi_snapshot_preview1::random_get` has not been defined

### ISSUE THREAD

**Issue by lok0613** [tessi/wasmex#422]
I was using a wasm file that built from javascript, it works fine with `wasmtime run` command/.

`** (EXIT from #PID<0.94.0>) bad return value: {:error, "unknown import: 'wasi_snapshot_preview1::random_get' has not been defined"}`
This error pops up when it run `{:ok, pid} = Wasmex.start_link(%{bytes: bytes})`

the soruce code of `test.wasm` file is actually from the demo code in https://github.com/Shopify/javy

**Comment by tessi** [comment]
It looks like you need to enable WASI. You can find [more about how to do this in our docs here](https://hexdocs.pm/wasmex/Wasmex.html#start_link/1-wasi). Can you try and report back, please? :)

**Comment by lok0613** [comment]
Yes I need WASL mode. After few attempts it still not work as expected. Again, I'm using the example from https://github.com/Shopify/javy.

When using `wasmtime` cli, this is the output
```bash
~$ echo '{ "n": 2, "bar": "baz" }' | wasmtime test.wasm
{"foo":3,"newBar":"baz!"}
```
Here is Elixir code with `wasmex`
```Elixir
# wasm.exs
bytes = File.read!("test.wasm")
{:ok, pid} = Wasmex.start_link(%{bytes: bytes, wasi: %Wasmex.Wasi.WasiOptions{
  args: ["{ \"n\": 2, \"bar\": \"baz\" }"]
}})
Wasmex.call_function(pid, :_start, []) |> IO.inspect()
```
When it runs, error occurs: 
```bash
~$ mix run wasm.exs
{:error,
 "Error during function excecution: `error while executing at wasm backtrace:\n    0: 0x13e0c - <unknown>!<wasm function 269>\n    1: 0x16bc - <unknown>!<wasm function 45>\n    2: 0x2406 - <unknown>!<wasm function 59>\n    3: 0xdd5b - <unknown>!<wasm function 174>\n    4: 0xd333 - <unknown>!<wasm function 173>\n    5:  0xdae - <unknown>!<wasm function 10>`."}
```
No matter I use `wasi: true` or `args` in `WasiOptions`, both got me the same error message.

Why the `wasmtime` cli isrunning fine but not in Elixir?

**Comment by tessi** [comment]
@lok0613 I believe this is not a problem with wasmex but with the how the WASM program is started (and it's bad error handling).

According to the javy README, this example WASM program needs input on STDIN. You providedd args instead.

I tried this locally and it works for me using stdin:

```
{:ok, stdin} = Wasmex.Pipe.new()
{:ok, stdout} = Wasmex.Pipe.new()
wasi_options = %Wasmex.Wasi.WasiOptions{stdin: stdin, stdout: stdout}
{:ok, pid } = Wasmex.start_link(%{bytes: File.read!("/Users/tessi/dev/javy/index.wasm"), wasi: wasi_options})
Wasmex.Pipe.write(stdin, ~s({ "n": 2, "bar": "baz" }))
Wasmex.Pipe.seek(stdin, 0)
{:ok, _} = Wasmex.call_function(pid, :_start, [])
Wasmex.Pipe.seek(stdout, 0)
Wasmex.Pipe.read(stdout) # => "{\"foo\":3,\"newBar\":\"baz!\"}"
```

**Comment by tessi** [comment]
closing this because it's not an issue with wasmex. thanks for trying wasmex out @lok0613 and for opening the ticket! it's always good to hear from people using it (and their problems) to learn about usability of wasmex. Also I learned about javy!
