### ISSUE TITLE
Upgrade to the wasmer rewrite

### ISSUE THREAD

**Issue by tessi** [tessi/wasmex#45]
According to the wasmer team, they 
>  are working on something very special: a new version of Wasmer with much better performance, supports for native compilation, has 4x better compilation speeds and a much more resilient API.

We got an invite to a preview of their work to be able to start adoption and could start experimenting with it.

**Comment by tessi** [comment]
In the meantime the people at wasmerio progressed on their rewrite: `Memory` is now Send+Sync :tada:  It makes one compilation error less.

Can't wait for https://github.com/wasmerio/wasmer-reborn/pull/135 to land - it is work to make more structures `Send+Sync`. We depend on it as rustler needs everything to be Send+Sync. When this lands, we are close to be functioning with the rewrite.

**Comment by syrusakbary** [comment]
The PR https://github.com/wasmerio/wasmer-reborn/pull/135 finally landed in master today 🎉

Hope this unblocks the issue!

**Comment by tessi** [comment]
Thanks @syrusakbary for the heads up. I hope to get some dev time soon when my daughter is asleep and I manage to stay awake :)

**Comment by tessi** [comment]
Update: It is compiling now and running mostly fine - the WIP code is pushed to the linked PR. What is still missing is access to memory from wrapped functions. The wasmer team has a neat trick to achieve this using function environments in their WASI implementation - given some time, I will copy and adapt their solution and see if it works for us.

**Comment by tessi** [comment]
Update: Did some more work - tests are green now. If wasmer-reborn is released, we should be ready to go 🎉 

```
❯ mix test
Compiling NIF crate :wasmex (native/wasmex)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
...............................................

Finished in 5.0 seconds
47 tests, 0 failures

Randomized with seed 959522
```

**Comment by tessi** [comment]
I am about to release v0.3.0 which includes support for wasmer 1.0 🎉
