### ISSUE TITLE
WebAssembly component support

### ISSUE THREAD

**Issue by superchris** [tessi/wasmex#491]
Hey all, I'm really excited about the [WebAssembly Components](https://component-model.bytecodealliance.org/) as a way to have a much higher level way to call into WebAssembly from Elixir. I'm a Rust newb (Elixir is my preferred language), but have managed to get simple examples of creating a component in JS and calling it from Rust using wasmtime to work. I'd like to investigate adding this support to wasmex, and wanted to check if there is interest in having such a feature.

**Comment by munjalpatel** [comment]
I think that would be a great addition @superchris

**Comment by superchris** [comment]
For those interested, making progress here: #630

**Comment by superchris** [comment]
Closed by [#630]
