### ISSUE TITLE
Calling WASM function should be async

### ISSUE THREAD

**Issue by tessi** [tessi/wasmex#6]
The [Erlang NIF documentation](http://erlang.org/doc/man/erl_nif.html) states that NIFs should avoid long running calls:

> A native function doing lengthy work before returning degrades responsiveness of the VM, and can cause miscellaneous strange behaviors. Such strange behaviors include, but are not limited to, extreme memory usage, and bad load balancing between schedulers. Strange behaviors that can occur because of lengthy work can also vary between Erlang/OTP releases.

Calling a WASM function (`Instance.call_exported_function`) is exactly such a long running call. We just don't know how long the WASM function will need to execute. We have some options here (e.g. dirty schedulers) but the most promising one is to make all function calls async. But making them async means we need to figure out a way to give the function calls result back into elixir land.

In #4 we discuss a way for "Rust land" to asynchronously talk to elixir. We should probably solve this issue in a similar way to #4 to keep the communication between rust and elixir consistent.

One possible solution is to use `GenServer` in elixir - one elixir process per instantiated WASM instance. The rust-part of that WASM instance could use [`enif_send`](http://erlang.org/doc/man/erl_nif.html#enif_send) to give function call results back to the elixir process of that instance.

We still need to find a good API to instantiate instances with `GenServer`. Also, it would be interesting whether the rust-side should also be asynchronous and how that could be achieved.

On the elixir side, I imagine we could use the (currently empty) `Wasmex` module to provide a high level API around `GenServer` instances:

```elixir
defmodule Wasmex do
  use GenServer

  @impl true
  def init(bytes) do
    {:ok, %{instance: Wasmex.Instance.from_bytes(bytes)}}
  end

  # this can be synchronous since it should be a fast call
  @impl true
  def handle_call({:exported_function_exists, name}, _from, %{instance: instance}) when is_binary(name) do
    {:reply, Wasmex.Instance.function_export_exists(instance, name), %{instance: instance}}
  end

  # this needs to start the function call and then immediately return. When the WASM part finished some form of callback/waiting/resolving needs to be done to inform the calling process of the function call result
  @impl true
  def handle_call({:call_function, name, params}, from, %{instance: instance}) do
    # ... ? this is where we need to get creative
  end

  def handle_info({:finished_function_execution, original_from, return_value}, state) do
    GenServer.reply(original_from, return_value)
    {:noreply, state}
  end
end
```

The `:call_function` handle_call could reply with a `{:noreply, , %{instance: instance}}` (possibly also setting the `:hibernate` flag according as outlined in [the docs](https://hexdocs.pm/elixir/GenServer.html#c:handle_call/3) and properly setting timeouts). When the rust part sends the "i am done, here is the result" message to the elixir process, it could use [`reply/2`](https://hexdocs.pm/elixir/GenServer.html#reply/2) to give the result back to the original caller.

Probably, this is best expressed with an image:

![async_function_call](https://user-images.githubusercontent.com/206108/75789771-7c353600-5d6a-11ea-9ae6-e2e87c12ee4a.png)

We would need someone experimenting with this idea and maybe implementing a PR.

**Comment by bamorim** [comment]
Hi @tessi. I’ve finally had time to look at the repository in more depth.
Now I agree with your plan of first making it async and then architecting the process structure.

My idea now is to start defining traits for the “resources” that Elixir would call (that is, `Instance` and `Memory`).

The reason to making them traits is that we can then play around with different strategies (one is to hold all state locally and just defer execution of particular calls to threads and the other is to keep an actor and then the resource would be just the “PID”)

So I think I’ll start by refactoring and defining these traits and moving your current implementation to a new struct and implement the trait as defined by the first approach.

That way we can defer the decisions on the async infrastructure for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tessi** [comment]
@bamorim I love this idea. I am torn between actix and async/await for the rust implementation. Implementing traits as a first step would be great so that we can both "play" with different solutions.

I'd be happy to see that PR. Please don't hesitate if I can provide any help.

**Comment by tessi** [comment]
@bamorim hope you're fine! It's been a while since our last messages. In the meantime, I experimented with async fn calls and merged a related PR. So this issue is technically closed.

However, I still like your idea of defining the common interface first if you still want to contribute.
